version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: kelvin
    container_name: newapp
    working_dir: app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
